name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    NODE_VERSION: "20"
    PNPM_VERSION: "8"

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            cache-key: ${{ steps.cache-key.outputs.key }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Generate cache key
              id: cache-key
              run: |
                  echo "key=${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT

            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ steps.cache-key.outputs.key }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Cache node_modules
              uses: actions/cache@v4
              id: node-modules-cache
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

    type-check:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Restore node_modules
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Type check
              run: pnpm run check-types

    build-check:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Restore node_modules
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Build check
              run: pnpm run build

    test:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - name: Restore node_modules
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

            - name: Run tests
              run: pnpm run test

    ci-status:
        runs-on: ubuntu-latest
        needs: [type-check, build-check, test]
        if: always()
        steps:
            - name: Check CI status
              run: |
                  echo "Type Check: ${{ needs.type-check.result }}"
                  echo "Build Check: ${{ needs.build-check.result }}"
                  echo "Test: ${{ needs.test.result }}"

                  if [[ "${{ needs.type-check.result }}" != "success" ||
                        "${{ needs.build-check.result }}" != "success" ||
                        "${{ needs.test.result }}" != "success" ]]; then
                    echo "❌ Some CI jobs failed"
                    exit 1
                  fi

                  echo "✅ All CI jobs completed successfully!"
