name: Obsidian E2E Test

on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]

jobs:
    e2e-test:
        # Windowsで実行します
        runs-on: windows-latest
        timeout-minutes: 15

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright browsers and dependencies
              run: pnpm playwright install --with-deps

            - name: Prepare E2E test environment
              # Windowsでもbashを使って e2e-setup.sh を実行します
              shell: bash
              run: |
                  # OBSIDIAN_VERSION を環境変数として e2e-setup.sh に渡します
                  export OBSIDIAN_VERSION="1.9.12"
                  ./e2e-setup.sh

            - name: Run Playwright tests
              # ここもbashで統一します
              shell: bash
              run: pnpm playwright test src/e2e/sandbox-vault.spec.mts --project=chromium

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report-windows
                  path: playwright-report/
                  retention-days: 30
