name: Obsidian E2E Test

on:
    workflow_dispatch:
    push:
        branches: ["main", "multiple-sandbox"]
    pull_request:
        branches: ["main", "multiple-sandbox"]

jobs:
    e2e-test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        timeout-minutes: 15

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm exec playwright install

            - name: Download Obsidian (Windows)
              if: runner.os == 'Windows'
              run: |
                  $OBSIDIAN_VERSION="1.9.12"
                  Invoke-WebRequest -Uri "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/Obsidian-${OBSIDIAN_VERSION}.exe" -OutFile "Obsidian.exe"
                  echo "OBSIDIAN_APP_PATH=${PWD}/Obsidian.exe" >> $env:GITHUB_ENV
              shell: pwsh

            - name: Download Obsidian (macOS)
              if: runner.os == 'macOS'
              run: |
                  OBSIDIAN_VERSION="1.9.12"
                  # macOS ARM64ランナー用にarm64版のDMGをダウンロード
                  curl -L "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_VERSION}/Obsidian-${OBSIDIAN_VERSION}.dmg" -o "Obsidian.dmg"
                  hdiutil attach Obsidian.dmg
                  echo "OBSIDIAN_APP_PATH=/Volumes/Obsidian/Obsidian.app" >> $GITHUB_ENV

            - name: Install jq (Windows)
              if: runner.os == 'Windows'
              # Git for Windowsにバンドルされているbashを使用するため、shellをbashに指定
              shell: bash
              run: |
                  curl -L -o /usr/bin/jq.exe https://github.com/jqlang/jq/releases/latest/download/jq-win64.exe

            - name: Prepare E2E test environment
              shell: bash
              run: bash e2e-setup.sh

            - name: Run Playwright tests
              run: pnpm playwright test src/e2e/sandbox-vault.spec.mts --project=electron
              env:
                  # この環境変数はPlaywrightの設定ファイル(playwright.config.ts)内で使用されることを想定
                  OBSIDIAN_APP_PATH: ${{ env.OBSIDIAN_APP_PATH }}
                  DEBUG: "pw:browser"

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report-${{ matrix.os }}
                  path: playwright-report/
                  retention-days: 30
