name: Obsidian E2E Test

on:
    workflow_dispatch:
    push:
        branches: ["main", "multiple-sandbox"]
    pull_request:
        branches: ["main", "multiple-sandbox"]

jobs:
    e2e-test:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, macos-latest]

        runs-on: ${{ matrix.os }}
        timeout-minutes: 15

        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Set up pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Install Playwright
              run: pnpm playwright install chromium

            - name: Install jq (Windows)
              if: runner.os == 'Windows'
              shell: bash
              run: |
                  curl -L -o jq.exe https://github.com/jqlang/jq/releases/latest/download/jq-win64.exe
                  echo "${{ github.workspace }}" >> $GITHUB_PATH

            - name: PWD # For debugging purposes
              shell: bash
              run: |
                  pwd

            - name: List project files # For debugging purposes
              shell: bash
              run: |
                  npx @telosh/filetree --exclude node_modules,.git

            - name: Prepare E2E test environment
              shell: bash
              run: |
                  chmod +x e2e-setup.sh
                  ./e2e-setup.sh

            - name: Run Playwright tests
              run: pnpm playwright test src/e2e/sandbox-vault.spec.mts --project=chromium
              env:
                  DEBUG: "pw:browser"

            - name: Upload Playwright report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report-${{ matrix.os }}
                  path: playwright-report/
                  retention-days: 30
